### ISSUE TITLE
Incompatible internal imports with "moduleResolution": "bundler" in Angular 20

### ISSUE THREAD

**Issue by pepearruda** [aws-amplify/amplify-ui#6592]
### Before creating a new issue, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [x] I have tried disabling all browser extensions or using a different browser
- [x] I have tried deleting the node_modules folder and reinstalling my dependencies
- [x] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Angular 20 / Angular CLI / Webpack 5

### Please describe your bug.

With the release of Angular 20, the default TypeScript moduleResolution has been updated to "bundler" to align with modern ESM-based tooling and module resolution strategies. After updating from Angular 19 to 20 and keeping moduleResolution as "bundler", I encountered several build-time errors in my project due to internal paths being referenced from the @aws-amplify/ui package.

```
X [ERROR] TS2307: Cannot find module '@aws-amplify/core/dist/esm/Hub/types' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@aws-amplify/ui/dist/types/helpers/authenticator/defaultAuthHubHandler.d.ts:15:108:
      15 │ ...r) => import("@aws-amplify/core/dist/esm/Hub/types").StopListen...
         ╵                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module '@aws-amplify/core/dist/esm/singleton/Auth/types' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@aws-amplify/ui/dist/types/machines/authenticator/defaultServices.d.ts:38:28:
      38 │ ...?: import("@aws-amplify/core/dist/esm/singleton/Auth/types").Co...
         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module '@aws-amplify/core/dist/esm/singleton/Auth/types' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@aws-amplify/ui/dist/types/machines/authenticator/defaultServices.d.ts:117:28:
      117 │ ...?: import("@aws-amplify/core/dist/esm/singleton/Auth/types").C...
          ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module '@aws-amplify/core/dist/esm/singleton/Auth/types' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@aws-amplify/ui/dist/types/machines/authenticator/defaultServices.d.ts:166:28:
      166 │ ...?: import("@aws-amplify/core/dist/esm/singleton/Auth/types").C...
          ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module '@aws-amplify/core/dist/esm/singleton/Auth/types' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@aws-amplify/ui/dist/types/machines/authenticator/defaultServices.d.ts:200:28:
      200 │ ...?: import("@aws-amplify/core/dist/esm/singleton/Auth/types").C...
          ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

#### Why This Matters:

Projects using modern build tools like Angular 20 (with "moduleResolution": "bundler") or tools like Vite and esbuild now rely on the exports field in package.json to determine module access. Deep imports into dist/esm/... are not resolved in this mode unless explicitly exported, causing these errors.

Temporarily reverting to "moduleResolution": "node" works, but breaks alignment with modern Angular tooling. For long-term compatibility, AWS Amplify packages should support "bundler" mode by exposing all referenced modules in the exports map.

Are you planning to update the amplify packages to support this?
I left some suggestions below on the expected behaviour section. Please feel free to consider them or suggest something else more aligned with your ideas.

Thanks for your work on Amplify!

#### Expected Behaviour:

These internal modules should either:

1. Be properly exported via the package's public API surface (e.g., exposed through the main exports field in package.json), or
2. Avoid referencing internal deep paths in .d.ts files that are not part of the public contract.

#### Suggested Fix:

Please update the @aws-amplify/core and @aws-amplify/ui packages to:
- Avoid referencing private/internal module paths in public type declarations
- Expose all needed modules/types via the exports field in package.json

### Help us reproduce the bug!

1. Create an Angular 20 project and add aws-amplify
2. Use Amplify authenticator features in your project
3. Run either "ng build" or "ng serve"

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

my package.json dependencies are:
```
"dependencies": {
    "@angular/animations": "^20.0.3",
    "@angular/cdk": "^20.0.3",
    "@angular/common": "^20.0.3",
    "@angular/compiler": "^20.0.3",
    "@angular/core": "^20.0.3",
    "@angular/forms": "^20.0.3",
    "@angular/material": "^20.0.3",
    "@angular/platform-browser": "^20.0.3",
    "@angular/platform-browser-dynamic": "^20.0.3",
    "@angular/router": "^20.0.3",
    "@aws-amplify/ui-angular": "^5.1.3",
    "aws-amplify": "^6.15.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular/build": "^20.0.2",
    "@angular/cli": "~20.0.2",
    "@angular/compiler-cli": "^20.0.3",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.8.3"
  }
```

**Comment by ahmedhamouda78** [comment]
Hey @pepearruda, we will look into this and get back to you as soon as we have an update

**Comment by VolkovH** [comment]
Hey @ahmedhamouda78, any update on this topic?
Since some of the Angular components like the HTTP Client do not work any more with the workaround "moduleResolution": "node" after the migration to Angular 21, this issue basically makes Amplify UI incompatible with Angular 21 in my opinion.
Or does anyone have a workaround for Angular 21 available?

**Comment by Simone319** [comment]
Hello @VolkovH , 

We are discussing with the team how to support this use case properly. In the meanwhile, `"moduleResolution": "node"` is one work around. And have you tried `skipLibCheck: true` that skips type checking in node_modules?
```
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```

Please try this and let us know how it works for you. We will update you once we have a permanent solution.
Thanks!

**Comment by VolkovH** [comment]
Using the `skipLibCheck` option seems to be a valid workaround, thanks!

**Comment by hman1148** [comment]
@pepearruda @ahmedhamouda78 I was experiencing this same issue as well. @Simone319 work around was I did and it seemed to work. Is this getting updated sometime soon? I tried doing moduleResolution: node but if you're working out of a Nx project, this will crash all your dependencies and not load any of them into the DOM.

**Comment by sarayev** [comment]
Hi @hman1148 , 

Nice to hear that the workaround worked for you as well. We'll get back to here once we have an update.
